/**
 * Creem API Client
 *
 * Thin wrapper around the Creem REST API. Uses native fetch so there's no
 * extra dependency to install.
 *
 * Authentication: every request sends the Creem API key in the `x-api-key`
 * header. The key is stored in STRIPE_API_KEY for naming compatibility with
 * the n8n-chat-ui project this integration was ported from.
 *
 * Base URL switches automatically between Creem's test and production
 * environments based on NODE_ENV:
 *   development → https://test-api.creem.io  (safe for testing, no real charges)
 *   production  → https://api.creem.io
 */

import { prisma } from "@/lib/db";
import type { CreemLicenseEntity } from "@/types/creem";
import * as crypto from "crypto";

const CREEM_BASE_URL =
  process.env.NODE_ENV === "development"
    ? "https://test-api.creem.io"
    : "https://api.creem.io";

/**
 * Characters used when generating a license key segment.
 * Ambiguous characters (0, O, I, 1, l) are intentionally excluded so the key
 * is easy to read and type without misreading a letter as a digit.
 */
const LICENSE_KEY_CHARS = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";

/**
 * Generates a single segment of `length` random characters from LICENSE_KEY_CHARS.
 * Uses crypto.randomBytes for cryptographically secure randomness — Math.random()
 * is not suitable here because license keys must be unpredictable.
 */
function generateSegment(length: number): string {
  return Array.from(crypto.randomBytes(length))
    .map((byte) => LICENSE_KEY_CHARS[byte % LICENSE_KEY_CHARS.length])
    .join("");
}

/**
 * Generates a new license key in the format: ARCO-XXXX-XXXX-XXXX-XXXX
 *
 * The "ARCO" prefix identifies the key as belonging to this product.
 * Each of the four segments is 4 characters drawn from a 32-character alphabet
 * (uppercase letters + digits, excluding ambiguous characters).
 *
 * Example output: ARCO-K7MN-Q3RB-9WXP-H4ZV
 *
 * This key is generated by us on the server when a purchase is confirmed,
 * then sent to Creem's activate endpoint to register it. The same key is
 * stored in the License table and ultimately delivered to the customer.
 */
export function generateLicenseKey(): string {
  return [
    "ARCO",
    generateSegment(4),
    generateSegment(4),
    generateSegment(4),
    generateSegment(4),
  ].join("-").trim();
}

/**
 * Generates a license key guaranteed to be unique in our database.
 *
 * Calls generateLicenseKey() in a loop, checking the License table after
 * each attempt. In practice a collision is astronomically unlikely (32-char
 * alphabet across 16 positions = 32^16 ≈ 1.2 × 10^24 possible keys), but we
 * verify anyway so there's no theoretical risk of issuing a duplicate key to
 * two different customers.
 *
 * The loop is capped at 10 attempts. If all 10 collide something is deeply
 * wrong with the random source, and we throw rather than loop indefinitely.
 */
export async function generateUniqueLicenseKey(): Promise<string> {
  const MAX_ATTEMPTS = 10;

  for (let attempt = 1; attempt <= MAX_ATTEMPTS; attempt++) {
    const key = generateLicenseKey();

    // Check whether this key already exists in the License table.
    const existing = await prisma.license.findUnique({ where: { key } });

    if (!existing) {
      return key; // Key is unique — safe to use.
    }

    console.warn(
      `License key collision on attempt ${attempt}/${MAX_ATTEMPTS}, regenerating...`,
    );
  }

  throw new Error(
    `Failed to generate a unique license key after ${MAX_ATTEMPTS} attempts.`,
  );
}

/**
 * Activates a license key with Creem and returns the full license entity.
 *
 * Called inside the checkout.completed webhook handler after we generate a
 * license key. Sending the key to Creem registers the activation against a
 * named instance (the customer's email) and returns the authoritative license
 * details (id, mode, limits, expiry) that we store in our License table.
 *
 * @param key          - The license key generated by generateLicenseKey()
 * @param instanceName - A label for this activation; we use the customer's email
 *                       so activations are traceable per customer in Creem's dashboard
 * @returns The activated CreemLicenseEntity with all fields needed to populate
 *          the License DB record
 * @throws  If the Creem API returns a non-2xx response
 */
export async function activateCreemLicense(
  key: string,
  instanceName: string,
): Promise<CreemLicenseEntity> {
  const response = await fetch(`${CREEM_BASE_URL}/v1/licenses/activate`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      // Creem API key — stored as STRIPE_API_KEY for compatibility with n8n-chat-ui
      "x-api-key": process.env.STRIPE_API_KEY!,
    },
    body: JSON.stringify({ key, instance_name: instanceName }),
  });

  if (!response.ok) {
    const error = await response.text();
    throw new Error(`Creem license activation failed: ${error}`);
  }

  return response.json() as Promise<CreemLicenseEntity>;
}
